CREATE TABLE IF NOT EXISTS "bbs_tag" (
                                         "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                         "content" varchar NOT NULL,
                                         "click_count" int,
                                         "sort" int NOT NULL,
                                         "status" int NOT NULL,
                                         "creator" varchar DEFAULT '',
                                         "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         "updater" varchar DEFAULT '',
                                         "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                         "deleted" bit NOT NULL DEFAULT FALSE,
                                         PRIMARY KEY ("id")
    ) COMMENT '标签表';

CREATE TABLE IF NOT EXISTS "bbs_classify" (
                                              "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                              "classify_name" varchar NOT NULL,
                                              "description" varchar,
                                              "click_count" int,
                                              "sort" int NOT NULL,
                                              "status" int NOT NULL,
                                              "creator" varchar DEFAULT '',
                                              "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                              "updater" varchar DEFAULT '',
                                              "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                              "deleted" bit NOT NULL DEFAULT FALSE,
                                              PRIMARY KEY ("id")
    ) COMMENT '分类表';

CREATE TABLE IF NOT EXISTS "bbs_article" (
                                             "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "title" varchar NOT NULL,
                                             "thumb" varchar,
                                             "summary" varchar,
                                             "content" varchar NOT NULL,
                                             "tag_ids" varchar NOT NULL,
                                             "click_count" int,
                                             "collect_count" int,
                                             "share_count" int,
                                             "is_original" bit NOT NULL,
                                             "author" varchar NOT NULL,
                                             "articles_part" varchar,
                                             "classify_id" varchar NOT NULL,
                                             "is_top" int NOT NULL,
                                             "level" bit,
                                             "open_comment" bit NOT NULL,
                                             "type" bit NOT NULL,
                                             "outside_link" varchar,
                                             "status" int NOT NULL,
                                             "creator" varchar DEFAULT '',
                                             "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             "updater" varchar DEFAULT '',
                                             "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                             "deleted" bit NOT NULL DEFAULT FALSE,
                                             PRIMARY KEY ("id")
    ) COMMENT '文章表';