CREATE TABLE IF NOT EXISTS "bbs_tag" (
                                         "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                         "content" varchar NOT NULL,
                                         "click_count" int,
                                         "sort" int NOT NULL,
                                         "status" int NOT NULL,
                                         "creator" varchar DEFAULT '',
                                         "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         "updater" varchar DEFAULT '',
                                         "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                         "deleted" bit NOT NULL DEFAULT FALSE,
                                         PRIMARY KEY ("id")
    ) COMMENT '标签表';

CREATE TABLE IF NOT EXISTS "bbs_classify" (
                                              "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                              "classify_name" varchar NOT NULL,
                                              "description" varchar,
                                              "click_count" int,
                                              "sort" int NOT NULL,
                                              "status" int NOT NULL,
                                              "creator" varchar DEFAULT '',
                                              "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                              "updater" varchar DEFAULT '',
                                              "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                              "deleted" bit NOT NULL DEFAULT FALSE,
                                              PRIMARY KEY ("id")
    ) COMMENT '分类表';